version: '3'
services:
  notebook:
    container_name: covid
    build: .
    ports:
      - "8888:8888"
    volumes:
      - D:\CloudStation\Cours\4ISD\chope_pas_le_covid:/home/covid/src
      - D:\data\covid:/home/covid/dataset
