version: '3'
services:
  notebook:
    container_name: ${CONTAINER_NAME}
    build: .
    ports:
      - "${JUPYTER_PORT}:8888"
    volumes:
      - ${SRC_PATH}:/home/covid/src
      - ${DATA_PATH}:/home/covid/dataset
