version: '3'
services:
  notebook:
    container_name: covid
    build: .
    ports:
      - "8888:8888"
    volumes:
      - /home/brami/Bureau/projet_zac_Antoine/data:/home/covid/dataset
      - /home/brami/Bureau/projet_zac_Antoine/chope_pas_le_covid:/home/covid/src

